package cep;
import rs.ac.uns.ftn.sbnz.rentcarservice.model.*;

declare PopularModelEvent
    @role(event)
    @expires(24h)
    marka: String
    reason: String
end;

rule "Popular model"
    when
        $re1: ReviewEvent($marka: marka)
        $num: Number(intValue >= 4) from accumulate(
            $re2: ReviewEvent(
            	this != $re1,
                marka == $marka
            ) over window:time( 24h ),
            count($re2)
        )
        not (PopularModelEvent(marka == $marka, reason == "Popular model"))
    then
        insert(new PopularModelEvent($marka, "Popular model"));
        System.out.println("Popular model: " + $marka);
end

