package cep;
import rs.ac.uns.ftn.sbnz.rentcarservice.model.*;

declare SuspiciousUserEvent
    @role(event)
    @expires(10m)
    email: String
    reason: String
end;

rule "Vise od 5 pokusaja za prijavu na sistem u 1 minutu od jednog korisnika"
    when
        $u1: LoginEvent($email: email)
        Number(intValue >= 4) from accumulate(
            $u2: LoginEvent(
                this != $u1, 
                email == $email
            ) over window:time( 1m ),
            count($u2)
        )
        not (SuspiciousUserEvent(email == $email, reason == "Previse pokusaja prijave na sistem"))
    then
        insert(new SuspiciousUserEvent($email, "Previse pokusaja prijave na sistem"));
                System.out.println("Neobicno korisnicko ponasanje (login) za korisnika: " + $email);

end