package rules.filter;
import java.util.List;
import java.util.ArrayList;
import rs.ac.uns.ftn.sbnz.rentcarservice.model.*;

global ArrayList<Auto> predlozeniAuti;


rule "Rangiranje predlozenih auta"
    agenda-group "rangiranje"
    salience( 98 - $bodovi)
    when
        $auto: Auto($bodovi:bodovi);
        $zahteviZaAuto: ZahteviZaAuto();
    then
        predlozeniAuti.add($auto);
        drools.getKnowledgeRuntime().setGlobal("predlozeniAuti", predlozeniAuti);
        System.out.println($auto.getNaziv() + " ima bodova: " +$bodovi);
end;

rule "Dodaj bodove za nizak budzet(3)"
    agenda-group "rangiranje"
    salience 100
    lock-on-active true
    when
        $auto: Auto($cena: cena <= 20, $bodovi: bodovi);
        $zahteviZaAuto: ZahteviZaAuto($budzet: budzet == Budzet.NISKI);
    then
        modify($auto){setBodovi($bodovi + 3);} 
        System.out.println("Dodaj bodove niski budzet 3");
end;

rule "Dodaj bodove za nizak budzet(1)"
    agenda-group "rangiranje"
    salience 100
    lock-on-active true
    when
        $auto: Auto($bodovi:bodovi, $cena: cena >= 20, cena < 60);
        $zahteviZaAuto: ZahteviZaAuto($budzet: budzet == Budzet.NISKI);
    then
        modify($auto){setBodovi($bodovi + 1);} 
end;

rule "Dodaj bodove za srednji budzet(3)"
    agenda-group "rangiranje"
    salience 100
    lock-on-active true
    when 
        $auto: Auto($bodovi:bodovi,cena < 60, cena > 20);
        $zahteviZaAuto: ZahteviZaAuto(budzet == Budzet.SREDNJI);
    then
        modify($auto){setBodovi($bodovi + 3);}
end

rule "Dodaj bodove srednji budzet(1)"
    agenda-group "rangiranje"
    salience 100
    lock-on-active true
    when
        $auto: Auto($bodovi:bodovi,cena < 20);
        $zahteviZaAuto: ZahteviZaAuto(budzet == Budzet.SREDNJI);
    then
        modify($auto){setBodovi($bodovi + 1);}
end

rule "Dodaj bodove visoki budzet(3)"
    agenda-group "rangiranje"
    salience 100
    lock-on-active true
    when
        $auto: Auto($bodovi:bodovi, cena > 60);
        $zahteviZaAuto: ZahteviZaAuto(budzet == Budzet.VISOK);
    then
        modify($auto){setBodovi($bodovi + 3);}
end

rule "Dodaj bodove visoki budzet(1)"
    agenda-group "rangiranje"
    salience 100
    lock-on-active true
    when
        $auto: Auto($bodovi:bodovi, cena < 60, cena > 20);
        $zahteviZaAuto: ZahteviZaAuto(budzet == Budzet.VISOK);
    then
        modify($auto){setBodovi($bodovi + 1);}
        System.out.println("Dodaj bodove visoki budzet");
end

rule "Bodovi za opremu"
    agenda-group "rangiranje"
    salience 100
    lock-on-active true
    when
        $auto: Auto($dodatnaOprema: dodatnaOprema, $bodovi:bodovi);
        $zahteviZaAuto: ZahteviZaAuto($dodatneOpreme: dodatneOpreme);
        $total: Number() from
            accumulate(DodatnaOprema($naziv: naziv memberOf $dodatneOpreme) from $dodatnaOprema, count($naziv))
    then
        modify($auto){setBodovi($bodovi + $total.intValue() * 2);}
        System.out.println("Total: " + $total);
        // System.out.println("Bodovi: " + $auto.getBodovi());
end

rule "Bodovi za udobnost"
    agenda-group "rangiranje"
    salience 100
    lock-on-active true
    when
        $auto: Auto($dodaciZaUdobnost: dodaciZaUdobnost, $bodovi:bodovi);
        $zahteviZaAuto: ZahteviZaAuto($dodaciZahtev:dodaciZaUdobnost);
        $total: Number() from
            accumulate(DodatakZaUdobnost($naziv: naziv memberOf $dodaciZahtev)
                        from $dodaciZaUdobnost, count($naziv))
    then
        modify($auto){setBodovi($bodovi + $total.intValue() * 2);}
        System.out.println("Total za udobnost: " + $total);
end

rule "Bodovi za eko voznju"
    agenda-group "rangiranje"
    salience 100
    lock-on-active true
    when
        $zahteviZaAuto: ZahteviZaAuto($goriva: tipGoriva);
        $auto: Auto($tipGoriva: tipGoriva memberOf $goriva, $bodovi:bodovi);
    then
        modify($auto){setBodovi($bodovi + 3)}
        System.out.println("eko voznja");
end

rule "Bodovi za eko voznju(oduzmi)"
    agenda-group "rangiranje"
    salience 100
    lock-on-active true
    when
        $zahteviZaAuto: ZahteviZaAuto($goriva: tipGoriva);
        $auto: Auto($tipGoriva: tipGoriva not memberOf $goriva, $bodovi:bodovi);
    then
        modify($auto){setBodovi($bodovi - 3)}
        System.out.println("nije eko voznja");
end

rule "Bodovi za karoseriju"
    agenda-group "rangiranje"
    salience 100
    lock-on-active true
    when
        $zahteviZaAuto: ZahteviZaAuto($moguceKaroserije:moguceKaroserije);
        $auto: Auto($karoserija:karoserija memberOf $moguceKaroserije, $bodovi:bodovi);
    then
        modify($auto){setBodovi($bodovi + 3);}
        System.out.println("odgovara karoserija");
end

rule "Bodovi za karoseriju(oduzmi)"
    agenda-group "rangiranje"
    salience 100
    lock-on-active true
    when
        $zahteviZaAuto: ZahteviZaAuto($moguceKaroserije:moguceKaroserije);
        $auto: Auto($karoserija:karoserija not memberOf $moguceKaroserije, $bodovi:bodovi);
    then
        modify($auto){setBodovi($bodovi - 3);}
        System.out.println("ne odgovara karoserija");
end

rule "Bodovi za broj sedista"
    agenda-group "rangiranje"
    salience 100
    lock-on-active true
    when
        $zahteviZaAuto: ZahteviZaAuto($minBrojSedista:minBrojSedista);
        $auto: Auto($brojSedista:brojSedista >= $minBrojSedista, $bodovi:bodovi);
    then
        modify($auto){setBodovi($bodovi + 3);}
        System.out.println("ok broj sedista");
end

rule "Bodovi za broj sedista(oduzmi)"
    agenda-group "rangiranje"
    salience 100
    lock-on-active true
    when
        $zahteviZaAuto: ZahteviZaAuto($minBrojSedista:minBrojSedista);
        $auto: Auto($brojSedista:brojSedista < $minBrojSedista, $bodovi:bodovi);
    then
        modify($auto){setBodovi($bodovi - 3);}
        System.out.println("nije ok broj sedista");
end